import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fetchPkgxPackage } from '../packages/fetch'
import { fetchPackageListFromGitHub } from '../utils'
import type { PkgxPackage } from '../types'

function sanitizeName(domain: string): string {
  return domain.replace(/[^a-zA-Z0-9]/g, '')
}

async function generate(): Promise<void> {
  const outputDir = path.join(process.cwd(), 'src/packages')
  if (!fs.existsSync(outputDir))
    fs.mkdirSync(outputDir, { recursive: true })

  const packages = await fetchPackageListFromGitHub(0)

  const importLines: string[] = []
  const exportLines: string[] = []
  const pantryEntries: string[] = []

  for (const pkg of packages) {
    try {
      const { packageInfo, fullDomainName } = await fetchPkgxPackage(pkg)
      const varName = `${sanitizeName(fullDomainName)}Package`
      const fileName = `${sanitizeName(fullDomainName)}.ts`
      const filePath = path.join(outputDir, fileName)
      const fileContent = `import type { PkgxPackage } from '../types'

/**
 * ${varName} information from pkgx.dev
 * Generated by tools/generatePackageData.ts
 */
export const ${varName}: PkgxPackage = ${JSON.stringify(packageInfo, null, 2)}
`
      fs.writeFileSync(filePath, fileContent)

      importLines.push(`import { ${varName} } from './${sanitizeName(fullDomainName)}'`)
      exportLines.push(`export * from './${sanitizeName(fullDomainName)}'`)
      pantryEntries.push(`  '${fullDomainName}': ${varName},`)
    }
    catch (error) {
      console.error(`Failed to fetch ${pkg}:`, error)
    }
  }

  const indexContent = `import type { PkgxPackage } from '../types'
${importLines.join('\n')}
export * from './fetch'
${exportLines.join('\n')}

export const pantry: Record<string, PkgxPackage> = {
${pantryEntries.join('\n')}
}
`
  fs.writeFileSync(path.join(outputDir, 'index.ts'), indexContent)
}

generate().catch((err) => {
  console.error('Generation failed:', err)
  process.exit(1)
})
